apiVersion: v1
kind: Pod
metadata:
  name: name-of-pod-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: bakedkookies/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP